<a href="https://colab.research.google.com/github/MihirKT/IrisClassification/blob/main/IrisClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [44]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [45]:
iris = load_iris() # load iris data from sklearn.datasets
data = iris.data  # Features
target = iris.target  # Species

In [46]:
print(iris.target)  # 0 for setosa, 1 for versicolor, 2 for virginica

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [47]:
print(iris.data) # sepal length, sepal width, petal length, petal width

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [48]:
# Dividing data into train and test dataset
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.35, random_state=75)

In [49]:
# Logistic regression for classification purpose
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [50]:
# Printing accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9811320754716981


In [51]:
import tensorflow as tf
from tensorflow import keras

In [52]:
y1_train = tf.keras.utils.to_categorical(y_train, num_classes=3)
y1_test = tf.keras.utils.to_categorical(y_test, num_classes=3)
X1_train = X_train / 255.0
X1_test = X_test / 255.0

In [53]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='relu', input_shape=(4,)),
    keras.layers.Dense(3, activation='softmax')  # Output layer with 3 classes
])

In [54]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(X1_train, y1_train, epochs=10, batch_size=25)

Epoch 1/10
4/4 [==============================] - 1s 4ms/step - loss: 1.0962 - accuracy: 0.3711
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0955 - accuracy: 0.3711
Epoch 3/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0947 - accuracy: 0.3711
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0944 - accuracy: 0.3711
Epoch 5/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0940 - accuracy: 0.3711
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0938 - accuracy: 0.3711
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0933 - accuracy: 0.3711
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0930 - accuracy: 0.3711
Epoch 9/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0927 - accuracy: 0.3711
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 1.0924 - accuracy: 0.3711


In [55]:
# Printing test accuracy
test_loss, test_acc = model.evaluate(X1_test, y1_test)
print("Test accuracy:", test_acc)

2/2 [==============================] - 0s 20ms/step - loss: 1.1032 - accuracy: 0.2642
Test accuracy: 0.2641509473323822
